name: Release on pushed tags

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag name
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update env.sample
        run: |
          cp docker/env.sample ${{ runner.temp }}
          sed -i 's/^TARANIS_TAG=.*/TARANIS_TAG=${{ env.tag }}/' ${{ runner.temp }}/env.sample

      - name: Verify new env.sample
        run: |
          cat ${{ runner.temp }}/env.sample

      - name: Get tag message
        id: get_tag_message
        run: |
          TAG_MESSAGE=$(git for-each-ref --format='%(contents)' "refs/tags/${{ env.tag }}")
          echo "tag_message=$TAG_MESSAGE" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          append_body: true
          body: ${{ env.tag_message }}
          files: |
            docker/compose.yml
            ${{ runner.temp }}/env.sample
