name: Release on pushed tags

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  # TODO: remove
  pull_request:

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag name
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git tag -a 2.1.0 -m "xyz feature is released in this tag.
          > My favourite text
          > Some text 
          > Some more text"
          echo "tag_message=$(git tag -n3 --format='%(contents)' 2.1.0)" >> $GITHUB_ENV
          

      - name: Update env.sample
        run: |
          cp docker/env.sample ${{ runner.temp }}
          sed -i 's/^TARANIS_TAG=.*/TARANIS_TAG=${{ env.tag }}/' ${{ runner.temp }}/env.sample

      - name: Verify new env.sample
        run: |
          cat ${{ runner.temp }}/env.sample

      - name: Get tag message
        id: get_tag_message
        run: |
          TAG_MESSAGE=$(git for-each-ref --format='%(contents)' "refs/tags/${{ env.tag }}")
          echo "tag_message=$TAG_MESSAGE" >> $GITHUB_ENV

    #   - name: Release
    #    uses: softprops/action-gh-release@v2
    #    if: startsWith(github.ref, 'refs/tags/')
    #    with:
    #      tag_name: ${{ env.tag }}
    #      release_name: ${{ env.tag }}
    #      body: ${{ env.tag_message }}
    #     generate_release_notes: true
    #    appendBody: true
    #   files: |
    #    docker/compose.yml
    #   ${{ runner.temp }}/env.sample
